### ISSUE TITLE
Stuck at Downloading wiki...

### ISSUE THREAD

**Issue by TheIdealis** [Noitidart/Enter-The-Gunbook#3]
If I try to start the app it is getting stuck at the start screen saying "Downloading wiki..."
I don't know how to get further information on a mobile device but I can tell that the app is not trying to download something.
I'am on a honor 10 with android 9.0.0.216.

**Comment by Noitidart** [comment]
Oh maybe they changed the website. I'll check it out.

**Comment by Noitidart** [comment]
I didn't get a chance to check this out yet, will try very soon. Will keep you updated.

**Comment by Noitidart** [comment]
It's weekend again. Going to take a look today.

**Comment by Noitidart** [comment]
Just released an update on Android. Will work on iOS update now.

**Comment by thomaslettau** [comment]
It works again, thanks a lot.

**Comment by Noitidart** [comment]
:)

I have to update for iOS too. I hope to do soon!
